eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Change Swagger URL from /swagger-ui.html to /api-docs
springdoc:
  swagger-ui:
    path: /doctor-service-api-docs   # <-- UI Page

  # for api docs path
  api-docs:
    path: /v3/doctor-service-api-docs  # <-- JSON Docs


